"""Public compatibility surface for range-server imports.

Legacy tests and callers import most service objects from ``range_server``
directly. Keep this module as reexports only so package imports do not create
runtime side effects beyond loading the referenced modules.
"""

from __future__ import annotations

from . import config
from .config import (
    AGGRESSIVE_DISCOVERY_SETTINGS,
    BACKEND_DEBUG_STDERR,
    BITTORRENT_ANNOUNCE_TO_ALL_TIERS,
    BITTORRENT_ANNOUNCE_TO_ALL_TRACKERS,
    BITTORRENT_DHT_ROUTERS,
    BITTORRENT_DISCOVERY_PROFILE,
    BITTORRENT_LISTEN_INTERFACES,
    BITTORRENT_PARALLEL_TRACKER_ANNOUNCES,
    BITTORRENT_PORT,
    BTIH_BASE32_PATTERN,
    BTIH_HEX_PATTERN,
    DEFAULT_DHT_ROUTERS,
    DEFAULT_PIECE_LENGTH,
    HEAD_TAIL_PIECES,
    IMAGE_SUBTITLE_EXTENSIONS,
    LIBTORRENT_DIR,
    LOGS_DIR,
    MAX_FILE_BYTES,
    MAX_JSON_BODY_BYTES,
    MAX_MAGNET_BYTES,
    MAX_METADATA_PATH_BYTES,
    MAX_RECENT_ALERTS,
    MAX_TORRENT_FILES,
    MAX_TOTAL_TORRENT_BYTES,
    MEDIA_ID_PATTERN,
    MIN_FREE_SPACE_BYTES,
    PORT,
    RANGE_CHUNK_BYTES,
    RANGE_PIECE_TIMEOUT_SECONDS,
    RANGE_PRELOAD_PIECES,
    RANGE_SERVER_CACHE_MODE,
    RANGE_WAIT_POLL_SECONDS,
    RESUME_SAVE_INTERVAL_SECONDS,
    SERVICE,
    SESSION_STATE_SAVE_INTERVAL_SECONDS,
    STORAGE_ROOT,
    TEXT_SUBTITLE_EXTENSIONS,
    TORRENTS_DIR,
    VIDEO_EXTENSIONS,
    configured_dht_bootstrap_nodes,
    configured_dht_routers,
    discovery_settings_for,
    normalize_cache_mode,
    normalize_discovery_profile,
    parse_optional_bool,
    profile_default_bool,
)
from .observability import backend_debug_enabled, backend_error, backend_exception, backend_log
from .models import (
    ApiError,
    Command,
    FileSnapshot,
    HttpByteRange,
    HttpResponse,
    Magnet,
    PieceTimeout,
    RawTorrentFile,
    SelectionResult,
    SourceReadError,
    TorrentSnapshot,
)
from .validation import header_value, normalize_btih, parse_file_index, parse_json_object, parse_magnet, validate_media_id
from .metadata import (
    build_file_snapshots,
    classify_path,
    decode_metadata_path,
    ensure_storage_policy,
    linked_subtitle_indices,
    range_content_type,
    safe_torrent_file_path,
    sanitize_metadata_path,
    selected_head_tail_pieces,
    torrent_error_code,
    validate_torrent_metadata_policy,
)
from .storage import ResumeStore, check_writable_dir, now_token, write_bytes_atomic, write_json_atomic
from .engine import LibtorrentEngine, TorrentEngine, default_libtorrent_listen_interfaces, detect_default_ipv4, enable_parallel_tracker_announces
from .range_streaming import (
    RangeStreamer,
    chunk_range_for,
    is_open_ended_http_range,
    iter_chunk_ranges,
    json_http_response,
    parse_http_range_header,
    pieces_for_file_range,
    preload_pieces_after,
    raise_range_not_satisfiable,
)
from .application import Application
from .http_server import Handler
from .main import build_application, main

# This list is the compatibility contract for older imports.
__all__ = [
    "config",
    "ApiError",
    "Magnet",
    "RawTorrentFile",
    "FileSnapshot",
    "TorrentSnapshot",
    "SelectionResult",
    "Command",
    "HttpByteRange",
    "HttpResponse",
    "PieceTimeout",
    "SourceReadError",
    "ResumeStore",
    "TorrentEngine",
    "LibtorrentEngine",
    "Application",
    "Handler",
    "RangeStreamer",
    "build_application",
    "main",
    "backend_debug_enabled",
    "backend_log",
    "backend_error",
    "backend_exception",
    "normalize_cache_mode",
    "normalize_discovery_profile",
    "parse_optional_bool",
    "profile_default_bool",
    "discovery_settings_for",
    "default_libtorrent_listen_interfaces",
    "detect_default_ipv4",
    "configured_dht_routers",
    "configured_dht_bootstrap_nodes",
    "enable_parallel_tracker_announces",
    "validate_media_id",
    "parse_magnet",
    "normalize_btih",
    "parse_json_object",
    "parse_file_index",
    "header_value",
    "sanitize_metadata_path",
    "decode_metadata_path",
    "classify_path",
    "build_file_snapshots",
    "validate_torrent_metadata_policy",
    "ensure_storage_policy",
    "linked_subtitle_indices",
    "selected_head_tail_pieces",
    "parse_http_range_header",
    "is_open_ended_http_range",
    "raise_range_not_satisfiable",
    "pieces_for_file_range",
    "preload_pieces_after",
    "chunk_range_for",
    "iter_chunk_ranges",
    "range_content_type",
    "safe_torrent_file_path",
    "json_http_response",
    "torrent_error_code",
    "write_json_atomic",
    "write_bytes_atomic",
    "check_writable_dir",
    "now_token",
]
__all__ += [
    "SERVICE", "STORAGE_ROOT", "TORRENTS_DIR", "LIBTORRENT_DIR", "LOGS_DIR", "PORT", "BACKEND_DEBUG_STDERR",
    "MEDIA_ID_PATTERN", "BTIH_HEX_PATTERN", "BTIH_BASE32_PATTERN", "MAX_MAGNET_BYTES", "MAX_JSON_BODY_BYTES",
    "MAX_TORRENT_FILES", "MAX_TOTAL_TORRENT_BYTES", "MAX_FILE_BYTES", "MAX_METADATA_PATH_BYTES",
    "MIN_FREE_SPACE_BYTES", "DEFAULT_PIECE_LENGTH", "HEAD_TAIL_PIECES", "RANGE_CHUNK_BYTES",
    "RANGE_PIECE_TIMEOUT_SECONDS", "RANGE_WAIT_POLL_SECONDS", "RANGE_PRELOAD_PIECES",
    "RESUME_SAVE_INTERVAL_SECONDS", "SESSION_STATE_SAVE_INTERVAL_SECONDS", "BITTORRENT_PORT",
    "BITTORRENT_LISTEN_INTERFACES", "DEFAULT_DHT_ROUTERS", "BITTORRENT_DHT_ROUTERS",
    "BITTORRENT_PARALLEL_TRACKER_ANNOUNCES", "BITTORRENT_ANNOUNCE_TO_ALL_TRACKERS",
    "BITTORRENT_ANNOUNCE_TO_ALL_TIERS", "BITTORRENT_DISCOVERY_PROFILE", "RANGE_SERVER_CACHE_MODE",
    "MAX_RECENT_ALERTS", "AGGRESSIVE_DISCOVERY_SETTINGS", "VIDEO_EXTENSIONS", "TEXT_SUBTITLE_EXTENSIONS",
    "IMAGE_SUBTITLE_EXTENSIONS",
]
