export const mockMovies = [
  {
    id: 1,
    title: 'The Matrix',
    year: 1999,
    rating: 8.7,
    genre: 'Science fiction',
    coverUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    watched: true,
  },
  {
    id: 2,
    title: 'Inception',
    year: 2010,
    rating: 8.8,
    genre: 'Thriller',
    coverUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    watched: false,
  },
  {
    id: 3,
    title: 'Interstellar',
    year: 2014,
    rating: 8.7,
    genre: 'Adventure',
    coverUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    watched: true,
  },
  {
    id: 4,
    title: 'Parasite',
    year: 2019,
    rating: 8.5,
    genre: 'Drama',
    coverUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    watched: false,
  },
  {
    id: 5,
    title: 'Mad Max: Fury Road',
    year: 2015,
    rating: 8.1,
    genre: 'Action',
    coverUrl: 'https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
    watched: false,
  },
  {
    id: 6,
    title: 'Spirited Away',
    year: 2001,
    rating: 8.6,
    genre: 'Animation',
    coverUrl: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    watched: true,
  },
  {
    id: 7,
    title: 'Blade Runner 2049',
    year: 2017,
    rating: 8.0,
    genre: 'Science fiction',
    coverUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    watched: false,
  },
  {
    id: 8,
    title: 'Dune',
    year: 2021,
    rating: 8.0,
    genre: 'Adventure',
    coverUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
    watched: false,
  },
  {
    id: 9,
    title: 'The Dark Knight',
    year: 2008,
    rating: 9.0,
    genre: 'Action',
    coverUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    watched: true,
  },
  {
    id: 10,
    title: 'Arrival',
    year: 2016,
    rating: 7.9,
    genre: 'Science fiction',
    coverUrl: 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
    watched: false,
  },
  {
    id: 11,
    title: 'Whiplash',
    year: 2014,
    rating: 8.5,
    genre: 'Drama',
    coverUrl: 'https://image.tmdb.org/t/p/w500/6uSPcdGNA2A6vJmCagXkvnutegs.jpg',
    watched: true,
  },
  {
    id: 12,
    title: 'Everything Everywhere All at Once',
    year: 2022,
    rating: 7.8,
    genre: 'Action',
    coverUrl: 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
    watched: false,
  },
  {
    id: 13,
    title: 'The Grand Budapest Hotel',
    year: 2014,
    rating: 8.1,
    genre: 'Drama',
    coverUrl: 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
    watched: false,
  },
  {
    id: 14,
    title: 'Joker',
    year: 2019,
    rating: 8.4,
    genre: 'Drama',
    coverUrl: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    watched: true,
  },
  {
    id: 15,
    title: 'Pulp Fiction',
    year: 1994,
    rating: 8.9,
    genre: 'Thriller',
    coverUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    watched: true,
  },
  {
    id: 16,
    title: 'The Social Network',
    year: 2010,
    rating: 7.8,
    genre: 'Drama',
    coverUrl: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
    watched: false,
  },
  {
    id: 17,
    title: 'Her',
    year: 2013,
    rating: 8.0,
    genre: 'Science fiction',
    coverUrl: 'https://image.tmdb.org/t/p/w500/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg',
    watched: false,
  },
  {
    id: 18,
    title: 'No Country for Old Men',
    year: 2007,
    rating: 8.2,
    genre: 'Thriller',
    coverUrl: 'https://image.tmdb.org/t/p/w500/bj1v6YKF8yHqA489VFfnQvOJpnc.jpg',
    watched: true,
  },
  {
    id: 19,
    title: 'Akira',
    year: 1988,
    rating: 8.0,
    genre: 'Animation',
    coverUrl: 'https://image.tmdb.org/t/p/w500/neZ0ykEsPqxamsX6o5QNUFILQrz.jpg',
    watched: false,
  },
  {
    id: 20,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: 2001,
    rating: 8.9,
    genre: 'Adventure',
    coverUrl: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    watched: true,
  },
]
