service: hypertube-api
image: 42-course/hypertube-api

servers:
  web:
    - 167.71.57.19

proxy:
  ssl: true
  host: fractalia.art
  app_port: 80

registry:
  server: ghcr.io
  username: 42-Course
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DATABASE_HOST: hypertube-api-db
    DATABASE_PORT: "5432"
    DATABASE_NAME: hypertube_production
    DATABASE_USERNAME: hypertube
    RAILS_MAX_THREADS: "5"
    RAILS_LOG_TO_STDOUT: "true"
    REDIS_URL: redis://hypertube-api-redis:6379/0
    FRONTEND_URL: https://fractalia.art
    API_URL: https://fractalia.art
    SMTP_HOST: smtp.gmail.com
    SMTP_PORT: "587"
    MAILER_FROM: noreply@fractalia.art
    PROWLARR_URL: https://prowlarr.pulgamecanica.com
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_PASSWORD
    - SECRET_KEY_BASE
    - JWT_SECRET_KEY
    - OMNIAUTH_42_CLIENT_ID
    - OMNIAUTH_42_CLIENT_SECRET
    - OMNIAUTH_GOOGLE_CLIENT_ID
    - OMNIAUTH_GOOGLE_CLIENT_SECRET
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - OMDB_API_KEY
    - TMDB_API_KEY
    - PROWLARR_API_KEY

accessories:
  db:
    image: postgres:16-alpine
    host: 167.71.57.19
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_DB: hypertube_production
        POSTGRES_USER: hypertube
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    host: 167.71.57.19
    port: "127.0.0.1:6379:6379"
    volumes:
      - /var/lib/redis/data:/data
